# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - name: "Hardhik Temperature"
      state_topic: "home/HardhikT-2025/sensor"
      unit_of_measurement: "Â°C"
      value_template: "{{ value_json.temp }}"

    - name: "Hardhik Humidity"
      state_topic: "home/HardhikT-2025/sensor"
      unit_of_measurement: "%"
      value_template: "{{ value_json.hum }}"

  binary_sensor:
    - name: "PIR Motion Detector"
      state_topic: "home/HardhikT-2025/sensor"
      payload_on: "1"
      payload_off: "0"
      value_template: "{{ value_json.motion }}"
      device_class: motion
